---
channel: edge
addons:
  adb:
    repository: hassio-addons/addon-adb
    target: adb
    image: ghcr.io/hassio-addons/adb/{arch}
  adguard:
    repository: hassio-addons/addon-adguard-home
    target: adguard
    image: ghcr.io/hassio-addons/adguard/{arch}
  aircast:
    repository: hassio-addons/addon-aircast
    target: aircast
    image: ghcr.io/hassio-addons/aircast/{arch}
  airsonos:
    repository: hassio-addons/addon-airsonos
    target: airsonos
    image: ghcr.io/hassio-addons/airsonos/{arch}
  appdaemon:
    repository: hassio-addons/addon-appdaemon
    target: appdaemon
    image: ghcr.io/hassio-addons/appdaemon/{arch}
  bitwarden:
    repository: hassio-addons/addon-bitwarden
    target: bitwarden
    image: ghcr.io/hassio-addons/bitwarden/{arch}
  bookstack:
    repository: hassio-addons/addon-bookstack
    target: bookstack
    image: ghcr.io/hassio-addons/bookstack/{arch}
  chrony:
    repository: hassio-addons/addon-chrony
    target: chrony
    image: ghcr.io/hassio-addons/chrony/{arch}
  example:
    repository: hassio-addons/addon-example
    target: example
    image: ghcr.io/hassio-addons/example/{arch}
  ftp:
    repository: hassio-addons/addon-ftp
    target: ftp
    image: ghcr.io/hassio-addons/ftp/{arch}
  foldingathome:
    repository: hassio-addons/addon-foldingathome
    target: foldingathome
    image: ghcr.io/hassio-addons/foldingathome/{arch}
  glances:
    repository: hassio-addons/addon-glances
    target: glances
    image: ghcr.io/hassio-addons/glances/{arch}
  grafana:
    repository: hassio-addons/addon-grafana
    target: grafana
    image: ghcr.io/hassio-addons/grafana/{arch}
  grocy:
    repository: hassio-addons/addon-grocy
    target: grocy
    image: ghcr.io/hassio-addons/grocy/{arch}
  home-panel:
    repository: hassio-addons/addon-home-panel
    target: home-panel
    image: ghcr.io/hassio-addons/home-panel/{arch}
  influxdb:
    repository: hassio-addons/addon-influxdb
    target: influxdb
    image: ghcr.io/hassio-addons/influxdb/{arch}
  jupyterlab:
    repository: hassio-addons/addon-jupyterlab
    target: jupyterlab
    image: ghcr.io/hassio-addons/jupyterlab/{arch}
  ledfx:
    repository: hassio-addons/addon-ledfx
    target: ledfx
    image: ghcr.io/hassio-addons/ledfx/{arch}
  log-viewer:
    repository: hassio-addons/addon-log-viewer
    target: log-viewer
    image: ghcr.io/hassio-addons/log-viewer/{arch}
  lutron-cert:
    repository: hassio-addons/addon-lutron-cert
    target: lutron-cert
    image: ghcr.io/hassio-addons/lutron-cert/{arch}
  matrix:
    repository: hassio-addons/addon-matrix
    target: matrix
    image: ghcr.io/hassio-addons/matrix/{arch}
  mopidy:
    repository: hassio-addons/addon-mopidy
    target: mopidy
    image: ghcr.io/hassio-addons/mopidy/{arch}
  motioneye:
    repository: hassio-addons/addon-motioneye
    target: motioneye
    image: ghcr.io/hassio-addons/motioneye/{arch}
  mqtt:
    repository: hassio-addons/addon-mqtt
    target: mqtt
    image: hassioaddons/mqtt-{arch}
  node-red:
    repository: hassio-addons/addon-node-red
    target: node-red
    image: ghcr.io/hassio-addons/node-red/{arch}
  nginxproxymanager:
    repository: hassio-addons/addon-nginx-proxy-manager
    target: proxy-manager
    image: ghcr.io/hassio-addons/nginxproxymanager/{arch}
  nut:
    repository: hassio-addons/addon-nut
    target: nut
    image: ghcr.io/hassio-addons/nut/{arch}
  phpmyadmin:
    repository: hassio-addons/addon-phpmyadmin
    target: phpmyadmin
    image: ghcr.io/hassio-addons/phpmyadmin/{arch}
  plex:
    repository: hassio-addons/addon-plex
    target: plex
    image: ghcr.io/hassio-addons/plex/{arch}
  prometheus:
    repository: hassio-addons/addon-prometheus
    target: prometheus
    image: hassioaddons/prometheus-{arch}
  portainer:
    repository: hassio-addons/addon-portainer
    target: portainer
    image: ghcr.io/hassio-addons/portainer/{arch}
  spotify:
    repository: hassio-addons/addon-spotify-connect
    target: spotify
    image: ghcr.io/hassio-addons/spotify/{arch}
  tasmoadmin:
    repository: hassio-addons/addon-tasmoadmin
    target: tasmoadmin
    image: ghcr.io/hassio-addons/tasmoadmin/{arch}
  tautulli:
    repository: hassio-addons/addon-tautulli
    target: tautulli
    image: ghcr.io/hassio-addons/tautulli/{arch}
  ssh:
    repository: hassio-addons/addon-ssh
    target: ssh
    image: ghcr.io/hassio-addons/ssh/{arch}
  sqlite-web:
    repository: hassio-addons/addon-sqlite-web
    target: sqlite-web
    image: ghcr.io/hassio-addons/sqlite-web/{arch}
  thelounge:
    repository: hassio-addons/addon-thelounge
    target: thelounge
    image: ghcr.io/hassio-addons/thelounge/{arch}
  tor:
    repository: hassio-addons/addon-tor
    target: tor
    image: ghcr.io/hassio-addons/tor/{arch}
  traccar:
    repository: hassio-addons/addon-traccar
    target: traccar
    image: ghcr.io/hassio-addons/traccar/{arch}
  unifi:
    repository: hassio-addons/addon-unifi
    target: unifi
    image: ghcr.io/hassio-addons/unifi/{arch}
  vscode:
    repository: hassio-addons/addon-vscode
    target: vscode
    image: ghcr.io/hassio-addons/vscode/{arch}
  vscode-remote:
    repository: hassio-addons/addon-vscode-remote
    target: vscode-remote
    image: ghcr.io/hassio-addons/vscode-remote/{arch}
  wireguard:
    repository: hassio-addons/addon-wireguard
    target: wireguard
    image: ghcr.io/hassio-addons/wireguard/{arch}
  zerotier:
    repository: hassio-addons/addon-zerotier
    target: zerotier
    image: ghcr.io/hassio-addons/zerotier/{arch}
  zwave2mqtt:
    repository: hassio-addons/addon-zwave2mqtt
    target: zwave2mqtt
    image: ghcr.io/hassio-addons/zwave2mqtt/{arch}
  zwavejs2mqtt:
    repository: hassio-addons/addon-zwavejs2mqtt
    target: zwavejs2mqtt
    image: ghcr.io/hassio-addons/zwavejs2mqtt/{arch}
