---
channel: edge
addons:
  adb:
    repository: hassio-addons/addon-adb
    target: adb
    image: hassioaddons/adb-{arch}
  adguard:
    repository: hassio-addons/addon-adguard-home
    target: adguard
    image: hassioaddons/adguard-{arch}
  aircast:
    repository: hassio-addons/addon-aircast
    target: aircast
    image: hassioaddons/aircast-{arch}
  airsonos:
    repository: hassio-addons/addon-airsonos
    target: airsonos
    image: hassioaddons/airsonos-{arch}
  appdaemon:
    repository: hassio-addons/addon-appdaemon
    target: appdaemon
    image: hassioaddons/appdaemon-{arch}
  bitwarden:
    repository: hassio-addons/addon-bitwarden
    target: bitwarden
    image: ghcr.io/hassio-addons/bitwarden/{arch}
  bookstack:
    repository: hassio-addons/addon-bookstack
    target: bookstack
    image: ghcr.io/hassio-addons/bookstack/{arch}
  chrony:
    repository: hassio-addons/addon-chrony
    target: chrony
    image: hassioaddons/chrony-{arch}
  example:
    repository: hassio-addons/addon-example
    target: example
    image: ghcr.io/hassio-addons/example/{arch}
  ftp:
    repository: hassio-addons/addon-ftp
    target: ftp
    image: hassioaddons/ftp-{arch}
  firefly-iii:
    repository: hassio-addons/addon-firefly-iii
    target: firefly-iii
    image: hassioaddons/firefly-iii-{arch}
  foldingathome:
    repository: hassio-addons/addon-foldingathome
    target: foldingathome
    image: hassioaddons/foldingathome-{arch}
  glances:
    repository: hassio-addons/addon-glances
    target: glances
    image: hassioaddons/glances-{arch}
  grafana:
    repository: hassio-addons/addon-grafana
    target: grafana
    image: hassioaddons/grafana-{arch}
  grocy:
    repository: hassio-addons/addon-grocy
    target: grocy
    image: hassioaddons/grocy-{arch}
  home-panel:
    repository: hassio-addons/addon-home-panel
    target: home-panel
    image: hassioaddons/home-panel-{arch}
  influxdb:
    repository: hassio-addons/addon-influxdb
    target: influxdb
    image: hassioaddons/influxdb-{arch}
  jupyterlablite:
    repository: hassio-addons/addon-jupyterlab-lite
    target: jupyterlab
    image: hassioaddons/jupyterlablite-{arch}
  ledfx:
    repository: hassio-addons/addon-ledfx
    target: ledfx
    image: hassioaddons/ledfx-{arch}
  log-viewer:
    repository: hassio-addons/addon-log-viewer
    target: log-viewer
    image: hassioaddons/log-viewer-{arch}
  lutron-cert:
    repository: hassio-addons/addon-lutron-cert
    target: lutron-cert
    image: hassioaddons/lutron-cert-{arch}
  matrix:
    repository: hassio-addons/addon-matrix
    target: matrix
    image: hassioaddons/matrix-{arch}
  mopidy:
    repository: hassio-addons/addon-mopidy
    target: mopidy
    image: hassioaddons/mopidy-{arch}
  motioneye:
    repository: hassio-addons/addon-motioneye
    target: motioneye
    image: hassioaddons/motioneye-{arch}
  mqtt:
    repository: hassio-addons/addon-mqtt
    target: mqtt
    image: hassioaddons/mqtt-{arch}
  node-red:
    repository: hassio-addons/addon-node-red
    target: node-red
    image: hassioaddons/node-red-{arch}
  nginxproxymanager:
    repository: hassio-addons/addon-nginx-proxy-manager
    target: proxy-manager
    image: hassioaddons/nginxproxymanager-{arch}
  nut:
    repository: hassio-addons/addon-nut
    target: nut
    image: hassioaddons/nut-{arch}
  phpmyadmin:
    repository: hassio-addons/addon-phpmyadmin
    target: phpmyadmin
    image: hassioaddons/phpmyadmin-{arch}
  plex:
    repository: hassio-addons/addon-plex
    target: plex
    image: hassioaddons/plex-{arch}
  prometheus:
    repository: hassio-addons/addon-prometheus
    target: prometheus
    image: hassioaddons/prometheus-{arch}
  portainer:
    repository: hassio-addons/addon-portainer
    target: portainer
    image: hassioaddons/portainer-{arch}
  spotify:
    repository: hassio-addons/addon-spotify-connect
    target: spotify
    image: hassioaddons/spotify-{arch}
  tasmoadmin:
    repository: hassio-addons/addon-tasmoadmin
    target: tasmoadmin
    image: hassioaddons/sonweb-{arch}
  tautulli:
    repository: hassio-addons/addon-tautulli
    target: tautulli
    image: hassioaddons/tautulli-{arch}
  ssh:
    repository: hassio-addons/addon-ssh
    target: ssh
    image: hassioaddons/ssh-{arch}
  sqlite-web:
    repository: hassio-addons/addon-sqlite-web
    target: sqlite-web
    image: hassioaddons/sqlite-web-{arch}
  thelounge:
    repository: hassio-addons/addon-thelounge
    target: thelounge
    image: hassioaddons/thelounge-{arch}
  tor:
    repository: hassio-addons/addon-tor
    target: tor
    image: ghcr.io/hassio-addons/tor/{arch}
  traccar:
    repository: hassio-addons/addon-traccar
    target: traccar
    image: hassioaddons/traccar-{arch}
  unifi:
    repository: hassio-addons/addon-unifi
    target: unifi
    image: ghcr.io/hassio-addons/unifi/{arch}
  vscode:
    repository: hassio-addons/addon-vscode
    target: vscode
    image: ghcr.io/hassio-addons/vscode/{arch}
  vscode-remote:
    repository: hassio-addons/addon-vscode-remote
    target: vscode-remote
    image: hassioaddons/vscode-remote-{arch}
  wireguard:
    repository: hassio-addons/addon-wireguard
    target: wireguard
    image: hassioaddons/wireguard-{arch}
  zerotier:
    repository: hassio-addons/addon-zerotier
    target: zerotier
    image: hassioaddons/zerotier-{arch}
  zwave2mqtt:
    repository: hassio-addons/addon-zwave2mqtt
    target: zwave2mqtt
    image: hassioaddons/zwave2mqtt-{arch}
