name: Home Panel
version: e40f676
slug: home-panel
description: A web frontend for controlling the home
url: https://github.com/hassio-addons/addon-home-panel
codenotary: codenotary@frenck.dev
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
ingress: true
ingress_stream: true
panel_icon: mdi:home
ports:
  80/tcp: null
ports_description:
  80/tcp: Web UI (Not required for Ingress)
map:
- config:rw
- ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
image: ghcr.io/hassio-addons/home-panel/{arch}
