arch:
- aarch64
- amd64
- armv7
backup_exclude:
- '**/Plex Media Server/Cache/**'
- '**/Plex Media Server/Plug-in Support/Caches/**'
- '**/Plex Media Server/Logs/**'
- '**/Plex Media Server/Crash Reports/**'
- '**/Plex Media Server/Diagnostics/**'
codenotary: codenotary@frenck.dev
description: Recorded media, live TV, online news, and podcasts ready to stream.
hassio_api: true
image: ghcr.io/hassio-addons/plex/{arch}
init: false
map:
- media:rw
- share:rw
- ssl
name: Plex Media Server
options:
  claim_code: ''
ports:
  3005/tcp: 3005
  32400/tcp: 32400
  32410/udp: 32410
  32412/udp: 32412
  32413/udp: 32413
  32414/udp: 32414
  32469/tcp: 32469
  8324/tcp: 8324
ports_description:
  3005/tcp: Plex Home Theater via Plex Companion
  32400/tcp: Plex Media Server Interface
  32410/udp: GDM network discovery
  32412/udp: GDM network discovery
  32413/udp: GDM network discovery
  32414/udp: GDM network discovery
  32469/tcp: Plex DLNA Server
  8324/tcp: Plex for Roku via Plex Companion
schema:
  claim_code: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
slug: plex
startup: services
url: https://github.com/hassio-addons/addon-plex
version: 3.2.1
webui: http://[HOST]:[PORT:32400]/web
