name: phpMyAdmin
version: '7464763'
slug: phpmyadmin
description: A web interface for the official MariaDB add-on
url: https://github.com/hassio-addons/addon-phpmyadmin
codenotary: codenotary@frenck.dev
ingress: true
ingress_stream: true
panel_icon: mdi:database
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
services:
- mysql:need
hassio_api: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  upload_limit: int?
image: ghcr.io/hassio-addons/phpmyadmin/{arch}
